require('packer_init')
-- Core settings and functionality
require('core/colors')
require('core/keymaps')
require('core/options')
-- Plugin settings
require('plugins/cmp')
require('plugins/gitsings')
require('plugins/lsp')
require('plugins/lualine')
require('plugins/null_ls')
require('plugins/telescope')
require('plugins/tree')
require('plugins/treesitter')
require('plugins/zenmode')
